# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0ctelemetry.v1\"\x7f\n\x0fSendDataRequest\x12\x10\n\x08truck_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x13\n\x0b\x65ngine_temp\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"4\n\x10SendDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2]\n\x10TelemetryService\x12I\n\x08SendData\x12\x1d.telemetry.v1.SendDataRequest\x1a\x1e.telemetry.v1.SendDataResponseB5Z3github.com/THETITAN220/GeoStream/proto/telemetry/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/THETITAN220/GeoStream/proto/telemetry/v1'
  _globals['_SENDDATAREQUEST']._serialized_start=33
  _globals['_SENDDATAREQUEST']._serialized_end=160
  _globals['_SENDDATARESPONSE']._serialized_start=162
  _globals['_SENDDATARESPONSE']._serialized_end=214
  _globals['_TELEMETRYSERVICE']._serialized_start=216
  _globals['_TELEMETRYSERVICE']._serialized_end=309
# @@protoc_insertion_point(module_scope)
