// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/telemetry/v1/telemetry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       string                 `protobuf:"bytes,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	EngineTemp    float64                `protobuf:"fixed64,5,opt,name=engine_temp,json=engineTemp,proto3" json:"engine_temp,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDataRequest) Reset() {
	*x = SendDataRequest{}
	mi := &file_proto_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataRequest) ProtoMessage() {}

func (x *SendDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataRequest.ProtoReflect.Descriptor instead.
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *SendDataRequest) GetTruckId() string {
	if x != nil {
		return x.TruckId
	}
	return ""
}

func (x *SendDataRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SendDataRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SendDataRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SendDataRequest) GetEngineTemp() float64 {
	if x != nil {
		return x.EngineTemp
	}
	return 0
}

func (x *SendDataRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SendDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDataResponse) Reset() {
	*x = SendDataResponse{}
	mi := &file_proto_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDataResponse) ProtoMessage() {}

func (x *SendDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDataResponse.ProtoReflect.Descriptor instead.
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *SendDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\"proto/telemetry/v1/telemetry.proto\x12\ftelemetry.v1\"\xbb\x01\n" +
	"\x0fSendDataRequest\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\tR\atruckId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x1f\n" +
	"\vengine_temp\x18\x05 \x01(\x01R\n" +
	"engineTemp\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"F\n" +
	"\x10SendDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2]\n" +
	"\x10TelemetryService\x12I\n" +
	"\bSendData\x12\x1d.telemetry.v1.SendDataRequest\x1a\x1e.telemetry.v1.SendDataResponseB5Z3github.com/THETITAN220/GeoStream/proto/telemetry/v1b\x06proto3"

var (
	file_proto_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_v1_telemetry_proto_rawDesc), len(file_proto_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_v1_telemetry_proto_rawDescData
}

var file_proto_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_telemetry_v1_telemetry_proto_goTypes = []any{
	(*SendDataRequest)(nil),  // 0: telemetry.v1.SendDataRequest
	(*SendDataResponse)(nil), // 1: telemetry.v1.SendDataResponse
}
var file_proto_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.TelemetryService.SendData:input_type -> telemetry.v1.SendDataRequest
	1, // 1: telemetry.v1.TelemetryService.SendData:output_type -> telemetry.v1.SendDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_telemetry_v1_telemetry_proto_init() }
func file_proto_telemetry_v1_telemetry_proto_init() {
	if File_proto_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_v1_telemetry_proto_rawDesc), len(file_proto_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_v1_telemetry_proto = out.File
	file_proto_telemetry_v1_telemetry_proto_goTypes = nil
	file_proto_telemetry_v1_telemetry_proto_depIdxs = nil
}
